import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// Product data from Guangzhou Huadu District Shiling Tongmenghao Outdoor Products Factory (TONMO)
// Source: Alibaba.com verified supplier, brand TONMO
const tonmoProducts = [
  {
    slug: 'tonmo-50l-tactical-backpack',
    sku: '9029-M',
    nameEn: '50L Tactical Backpack 1000D Nylon MOLLE',
    nameZh: '50L战术背包1000D尼龙MOLLE系统',
    descriptionEn: 'Large capacity tactical backpack with 1000D nylon construction and MOLLE system. Waterproof, durable, and designed for extended outdoor missions. Features multiple compartments, padded straps, and heavy-duty zippers.',
    descriptionZh: '大容量战术背包，采用1000D尼龙材料和MOLLE系统。防水耐用，适合长时间户外任务。配备多个隔层、加厚肩带和重型拉链。',
    shortDescEn: '50L tactical backpack with 1000D nylon and MOLLE system',
    shortDescZh: '50L战术背包，1000D尼龙+MOLLE系统',
    categorySlug: 'tactical-backpacks',
    isFeatured: true,
    sortOrder: 10,
    moq: 50,
    specifications: {
      'Material': '1000D Nylon',
      'Capacity': '50L',
      'System': 'MOLLE',
      'Lining': 'Polyester',
      'Hardware': 'Heavy-duty zippers',
      'Color': 'Camo / Black / Khaki',
    },
  },
  {
    slug: 'tonmo-34l-tactical-backpack',
    sku: 'TM01038',
    nameEn: '34L Tactical Backpack 900D Polyester MOLLE',
    nameZh: '34L战术背包900D聚酯MOLLE系统',
    descriptionEn: 'Versatile 34L tactical backpack with 900D high-density polyester construction. Features MOLLE system, waterproof design, and comfortable padded back panel. Ideal for hiking, camping, and tactical training.',
    descriptionZh: '多功能34L战术背包，采用900D高密度聚酯材料。配备MOLLE系统、防水设计和舒适加厚背板。适合徒步、露营和战术训练。',
    shortDescEn: '34L tactical backpack with 900D polyester and MOLLE',
    shortDescZh: '34L战术背包，900D聚酯+MOLLE系统',
    categorySlug: 'tactical-backpacks',
    isFeatured: true,
    sortOrder: 11,
    moq: 50,
    specifications: {
      'Material': '900D High-Density Polyester',
      'Capacity': '34L',
      'System': 'MOLLE',
      'Waterproof': 'Yes',
      'Colors': 'Camo / Solid colors',
      'Custom Logo': 'Available',
    },
  },
  {
    slug: 'tonmo-3-day-assault-pack',
    sku: 'TM01032',
    nameEn: '3-Day Assault Backpack 1000D Nylon 30L',
    nameZh: '3天突击背包1000D尼龙30L',
    descriptionEn: 'Tactical 3-day assault backpack made from 1000D nylon with MOLLE system. Compact yet spacious 25-30L capacity. Anti-theft design, waterproof, with multiple compartments for organized gear storage.',
    descriptionZh: '战术3天突击背包，采用1000D尼龙和MOLLE系统。紧凑但宽敞的25-30L容量。防盗设计，防水，多隔层有序存放装备。',
    shortDescEn: '3-day assault pack 30L, 1000D nylon MOLLE',
    shortDescZh: '3天突击包30L，1000D尼龙MOLLE',
    categorySlug: 'tactical-backpacks',
    isFeatured: false,
    sortOrder: 12,
    moq: 50,
    specifications: {
      'Material': '1000D Nylon / Denim',
      'Capacity': '25-30L',
      'System': 'MOLLE',
      'Lining': 'Polyester',
      'Anti-theft': 'Yes',
      'Waterproof': 'Yes',
    },
  },
  {
    slug: 'tonmo-xpac-tactical-backpack',
    sku: 'TM01015',
    nameEn: 'X-PAC Tactical Backpack 16L Lightweight',
    nameZh: 'X-PAC战术背包16L轻量化',
    descriptionEn: 'Lightweight tactical backpack made with X-PAC laminate fabric. Waterproof and durable yet ultra-light at 16L capacity. Perfect for short missions, EDC, and urban tactical use.',
    descriptionZh: '轻量化战术背包，采用X-PAC层压面料。防水耐用，超轻16L容量。适合短途任务、日常携带和城市战术用途。',
    shortDescEn: '16L X-PAC lightweight tactical backpack',
    shortDescZh: '16L X-PAC轻量化战术背包',
    categorySlug: 'tactical-backpacks',
    isFeatured: false,
    sortOrder: 13,
    moq: 2,
    specifications: {
      'Material': 'X-PAC Laminate / Nylon',
      'Capacity': '16L',
      'Waterproof': 'Yes',
      'Weight': 'Ultra-lightweight',
      'Closure': 'Zipper',
      'Style': 'Urban tactical',
    },
  },
  {
    slug: 'tonmo-30l-solid-tactical-backpack',
    sku: '20183',
    nameEn: '30L Solid Color Tactical Backpack YKK UTX',
    nameZh: '30L纯色战术背包YKK UTX五金',
    descriptionEn: 'Premium tactical backpack with YKK zippers and UTX hardware. Solid color design with 30L capacity. Anti-theft, waterproof, and built for long-lasting durability. Suitable for outdoor training, hunting, and tactical operations.',
    descriptionZh: '优质战术背包，配备YKK拉链和UTX五金扣件。纯色设计，30L容量。防盗防水，经久耐用。适合户外训练、狩猎和战术行动。',
    shortDescEn: '30L tactical backpack YKK UTX premium hardware',
    shortDescZh: '30L战术背包YKK UTX premium五金',
    categorySlug: 'tactical-backpacks',
    isFeatured: true,
    sortOrder: 14,
    moq: 100,
    specifications: {
      'Material': 'Nylon',
      'Capacity': '30L',
      'Zipper': 'YKK',
      'Hardware': 'UTX Hasp',
      'Waterproof': 'Yes',
      'Anti-theft': 'Yes',
    },
  },
  {
    slug: 'tonmo-85l-assault-backpack',
    sku: 'TM01110',
    nameEn: '85L Large Capacity Assault Backpack',
    nameZh: '85L大容量突击背包',
    descriptionEn: 'Extra-large 85L assault backpack designed for extended field operations. MOLLE system for modular attachment, waterproof construction, and reinforced stitching. Ideal for military expeditions and long-duration missions.',
    descriptionZh: '超大型85L突击背包，专为长时间野外行动设计。MOLLE系统可模块化挂载，防水结构，加固缝线。适合军事远征和长期任务。',
    shortDescEn: '85L extra-large assault backpack MOLLE',
    shortDescZh: '85L超大型突击背包MOLLE',
    categorySlug: 'tactical-backpacks',
    isFeatured: false,
    sortOrder: 15,
    moq: 10,
    specifications: {
      'Material': 'Nylon',
      'Capacity': '85L',
      'System': 'MOLLE',
      'Waterproof': 'Yes',
      'Suitable': 'Expedition / Long missions',
    },
  },
  {
    slug: 'tonmo-55l-3d-anti-theft-backpack',
    sku: 'TM01111',
    nameEn: '55L 3D Anti-theft MOLLE Backpack',
    nameZh: '55L 3D防盗MOLLE背包',
    descriptionEn: 'Large 55L tactical backpack with 3D anti-theft design. MOLLE system compatible, waterproof, with ergonomic carrying system. Suitable for camping, hiking, and tactical training.',
    descriptionZh: '大型55L战术背包，3D防盗设计。兼容MOLLE系统，防水，人体工学背负系统。适合露营、徒步和战术训练。',
    shortDescEn: '55L anti-theft MOLLE tactical backpack',
    shortDescZh: '55L防盗MOLLE战术背包',
    categorySlug: 'tactical-backpacks',
    isFeatured: false,
    sortOrder: 16,
    moq: 10,
    specifications: {
      'Material': 'Nylon',
      'Capacity': '55L',
      'System': 'MOLLE',
      'Anti-theft': '3D Design',
      'Waterproof': 'Yes',
      'Use': 'Camping / Hiking / Tactical',
    },
  },
  {
    slug: 'tonmo-25l-tactical-backpack',
    sku: 'TM01029',
    nameEn: '25L Tactical Backpack 1000D Nylon Camo',
    nameZh: '25L战术背包1000D尼龙迷彩',
    descriptionEn: 'Compact 25L tactical backpack constructed from 1000D nylon with camouflage pattern. MOLLE system for expansion, waterproof polyester lining, and lightweight design for fast-paced operations.',
    descriptionZh: '紧凑型25L战术背包，1000D尼龙迷彩图案。MOLLE系统可扩展，防水聚酯内衬，轻量化设计适合快速行动。',
    shortDescEn: '25L camo tactical backpack 1000D nylon',
    shortDescZh: '25L迷彩战术背包1000D尼龙',
    categorySlug: 'tactical-backpacks',
    isFeatured: false,
    sortOrder: 17,
    moq: 50,
    specifications: {
      'Material': '1000D Nylon',
      'Capacity': '25L',
      'Pattern': 'Camo',
      'Lining': 'Waterproof Polyester',
      'System': 'MOLLE',
      'Weight': 'Lightweight',
    },
  },
  {
    slug: 'tonmo-cordura-tactical-backpack',
    sku: '20183-6',
    nameEn: 'Cordura Tactical Backpack 40L Waterproof',
    nameZh: 'Cordura战术背包40L防水',
    descriptionEn: 'Premium tactical backpack made from Cordura fabric with 30-40L capacity. Features YKK zippers, UTX hardware, MOLLE system, and laser-cut attachment panels. Built for demanding tactical environments.',
    descriptionZh: '优质Cordura面料战术背包，30-40L容量。配备YKK拉链、UTX五金、MOLLE系统和激光切割挂载面板。专为严苛战术环境打造。',
    shortDescEn: '40L Cordura tactical backpack with laser-cut MOLLE',
    shortDescZh: '40L Cordura战术背包激光切割MOLLE',
    categorySlug: 'tactical-backpacks',
    isFeatured: true,
    sortOrder: 18,
    moq: 100,
    specifications: {
      'Material': 'Cordura Nylon',
      'Capacity': '30-40L',
      'Zipper': 'YKK',
      'Hardware': 'UTX',
      'System': 'Laser-cut MOLLE',
      'Waterproof': 'Yes',
    },
  },
  // Tactical Vests & Plate Carriers
  {
    slug: 'tonmo-500d-combat-vest',
    sku: '9073-MC',
    nameEn: '500D Nylon MOLLE Tactical Combat Vest / Plate Carrier',
    nameZh: '500D尼龙MOLLE战术作战背心/板 carrier',
    descriptionEn: 'Professional tactical combat vest and plate carrier made from 500D nylon with full MOLLE system. Features camouflage pattern, adjustable fit, and 1.7kg lightweight design. Compatible with standard ballistic plates for maximum protection.',
    descriptionZh: '专业战术作战背心/板 carrier，500D尼龙全MOLLE系统。迷彩图案，可调节尺寸，1.7kg轻量化设计。兼容标准防弹板，提供最大保护。',
    shortDescEn: '500D nylon MOLLE tactical combat vest plate carrier',
    shortDescZh: '500D尼龙MOLLE战术作战背心板 carrier',
    categorySlug: 'personal-protection',
    isFeatured: true,
    sortOrder: 20,
    moq: 200,
    isCustomizable: true,
    specifications: {
      'Material': '500D Nylon',
      'System': 'Full MOLLE',
      'Weight': '1.7 kg',
      'Pattern': 'Camo CP',
      'Custom Logo': 'Available',
      'Plate Compatible': 'Yes',
    },
  },
  {
    slug: 'tonmo-detachable-tactical-vest',
    sku: 'GB19',
    nameEn: 'Detachable Tactical Vest Multi-Functional GB19',
    nameZh: '可拆卸战术背心多功能GB19',
    descriptionEn: 'Lightweight detachable tactical vest made from Oxford cloth. Multi-functional design for outdoor training, missions, and combat. Features multiple pockets, adjustable fit, and OEM/ODM customization available.',
    descriptionZh: '轻便可拆卸战术背心，牛津布面料。多功能设计，适用于户外训练、任务和作战。多口袋设计，可调节尺寸，支持OEM/ODM定制。',
    shortDescEn: 'Detachable multi-functional tactical vest Oxford cloth',
    shortDescZh: '可拆卸多功能战术背心牛津布',
    categorySlug: 'personal-protection',
    isFeatured: false,
    sortOrder: 21,
    moq: 100,
    isCustomizable: true,
    specifications: {
      'Material': 'Oxford Cloth',
      'Dimensions': '50×15×49 cm',
      'Weight': '1.8 kg',
      'Design': 'Detachable',
      'Custom': 'OEM/ODM Available',
      'Use': 'Training / Combat',
    },
  },
  // Tactical Slings
  {
    slug: 'tonmo-double-point-tactical-sling',
    sku: 'TM09089',
    nameEn: 'Double Point Tactical Sling Heavy Duty Adjustable',
    nameZh: '双点战术吊索重型可调',
    descriptionEn: 'Heavy-duty double point tactical sling made from polyester webbing. Quick-detach mechanism, fully adjustable length, and durable metal hardware. Suitable for rifles, shotguns, and tactical training.',
    descriptionZh: '重型双点战术吊索，聚酯织带。快速分离机制，长度可调，耐用金属五金。适用于步枪、霰弹枪和战术训练。',
    shortDescEn: 'Heavy-duty double point tactical sling adjustable',
    shortDescZh: '重型双点战术吊索可调节',
    categorySlug: 'security-equipment',
    isFeatured: false,
    sortOrder: 30,
    moq: 200,
    specifications: {
      'Material': 'Polyester Webbing',
      'Type': 'Double Point',
      'Feature': 'Quick Detach',
      'Adjustable': 'Yes',
      'Hardware': 'Heavy-duty Metal',
      'Color': 'Black / Camo',
    },
  },
  {
    slug: 'tonmo-trap-m3-tactical-sling',
    sku: 'TM09089-M3',
    nameEn: 'TONMO Trap M3 Tactical Sling Quick Detach',
    nameZh: 'TONMO Trap M3战术吊索快速分离',
    descriptionEn: 'Premium Trap M3 tactical sling with quick-detach swivels. Polyester webbing construction with heavy-duty stitching. Adjustable for various carrying positions. Ideal for tactical shooting and hunting.',
    descriptionZh: '优质Trap M3战术吊索，快速分离旋转扣。聚酯织布结构，重型缝线。可调节多种携带位置。适合战术射击和狩猎。',
    shortDescEn: 'Trap M3 tactical sling quick detach adjustable',
    shortDescZh: 'Trap M3战术吊索快速分离可调',
    categorySlug: 'security-equipment',
    isFeatured: false,
    sortOrder: 31,
    moq: 200,
    specifications: {
      'Material': 'Polyester Webbing',
      'Model': 'Trap M3',
      'Feature': 'Quick Detach Swivels',
      'Adjustable': 'Yes',
      'Use': 'Rifle / Shotgun',
      'Color': 'Black / Coyote',
    },
  },
  // Tactical Belts
  {
    slug: 'tonmo-1.5-tactical-belt',
    sku: '901-Q',
    nameEn: '1.5" Heavy Duty Tactical Nylon Belt',
    nameZh: '1.5英寸重型战术尼龙腰带',
    descriptionEn: 'Durable 1.5-inch tactical nylon belt with heavy-duty metal buckle. Reinforced stitching for load-bearing applications. Suitable for uniform, duty carry, and outdoor activities.',
    descriptionZh: '耐用的1.5英寸战术尼龙腰带，重型金属扣。加固缝线可用于承载。适合制服、执勤携带和户外活动。',
    shortDescEn: '1.5" heavy duty tactical nylon belt metal buckle',
    shortDescZh: '1.5英寸重型战术尼龙腰带金属扣',
    categorySlug: 'security-equipment',
    isFeatured: false,
    sortOrder: 40,
    moq: 200,
    specifications: {
      'Material': 'Nylon',
      'Width': '1.5 inches',
      'Buckle': 'Heavy-duty Metal',
      'Stitching': 'Reinforced',
      'Color': 'Black / Khaki / OD Green',
      'Use': 'Duty / Outdoor',
    },
  },
  {
    slug: 'tonmo-cqb-battle-belt',
    sku: 'CQB-001',
    nameEn: 'Customizable Polyester Battle Belt CQB',
    nameZh: '可定制聚酯战斗腰带CQB',
    descriptionEn: 'Tactical CQB battle belt made from durable polyester webbing. Fully adjustable with MOLLE compatibility for attaching pouches and accessories. Suitable for training, airsoft, and tactical operations.',
    descriptionZh: '战术CQB战斗腰带，耐用聚酯织带。完全可调，兼容MOLLE系统挂载包袋和配件。适合训练、气枪和战术行动。',
    shortDescEn: 'Adjustable polyester battle belt MOLLE compatible',
    shortDescZh: '可调聚酯战斗腰带MOLLE兼容',
    categorySlug: 'security-equipment',
    isFeatured: false,
    sortOrder: 41,
    moq: 200,
    specifications: {
      'Material': 'Polyester Webbing',
      'Adjustable': 'Yes',
      'System': 'MOLLE Compatible',
      'Color': 'Khaki / Camo / Black',
      'Custom': 'Logo / Size Available',
      'Use': 'Training / CQB / Duty',
    },
  },
  // Tactical Pouches & Utilities
  {
    slug: 'tonmo-1000d-utility-pouch',
    sku: 'TM02001',
    nameEn: '1000D Nylon Tactical Utility Pouch MOLLE',
    nameZh: '1000D尼龙战术工具包MOLLE',
    descriptionEn: 'Heavy-duty utility pouch made from 1000D nylon with 420D lining. MOLLE compatible for belt or vest attachment. Waterproof with drainage grommet. Ideal for magazines, radios, and small gear.',
    descriptionZh: '重型工具包，1000D尼龙+420D内衬。MOLLE兼容可挂载腰带或背心。防水带排水孔。适合弹匣、对讲机和小型装备。',
    shortDescEn: '1000D nylon MOLLE utility pouch waterproof',
    shortDescZh: '1000D尼龙MOLLE工具包防水',
    categorySlug: 'security-equipment',
    isFeatured: false,
    sortOrder: 50,
    moq: 200,
    specifications: {
      'Material': '1000D Nylon / 420D Lining',
      'System': 'MOLLE',
      'Waterproof': 'Yes',
      'Drainage': 'Grommet',
      'Use': 'Magazines / Radio / Gear',
      'Color': 'Camo / Black',
    },
  },
  {
    slug: 'tonmo-tactical-waist-pouch',
    sku: 'TM02002',
    nameEn: 'Tactical Waist Pouch / Cell Phone Bag MOLLE',
    nameZh: '战术腰包/手机袋MOLLE',
    descriptionEn: 'Compact tactical waist pouch for EDC carry. MOLLE compatible for belt or vest mounting. Perfect for cell phone, wallet, keys, and small essentials. Quick-access design with secure closure.',
    descriptionZh: '紧凑型战术腰包，日常携带。MOLLE兼容可挂载腰带或背心。适合手机、钱包、钥匙和小物件。快速存取设计，安全闭合。',
    shortDescEn: 'Compact MOLLE waist pouch EDC cell phone bag',
    shortDescZh: '紧凑型MOLLE腰包EDC手机袋',
    categorySlug: 'security-equipment',
    isFeatured: false,
    sortOrder: 51,
    moq: 100,
    specifications: {
      'Material': 'Nylon',
      'System': 'MOLLE',
      'Closure': 'Secure zipper',
      'Use': 'Phone / Wallet / EDC',
      'Color': 'Camo / Black',
    },
  },
  // Tactical Medical Pouch
  {
    slug: 'tonmo-medical-fak-pouch',
    sku: 'TM02003',
    nameEn: 'Professional Tactical Medical FAK Pouch',
    nameZh: '专业战术急救包FAK袋',
    descriptionEn: 'Professional tactical medical pouch designed for First Aid Kits. Large capacity with MOLLE backing. Organized internal compartments for medical supplies. Quick-access pull tab for emergency situations.',
    descriptionZh: '专业战术急救包袋，专为FAK设计。大容量，MOLLE底板。内置整理隔层放置医疗用品。紧急情况快速拉取设计。',
    shortDescEn: 'Tactical medical FAK pouch MOLLE large capacity',
    shortDescZh: '战术急救FAK袋MOLLE大容量',
    categorySlug: 'rescue-equipment',
    isFeatured: false,
    sortOrder: 60,
    moq: 100,
    specifications: {
      'Material': 'Nylon / Polyester',
      'System': 'MOLLE Backing',
      'Capacity': 'Large',
      'Closure': 'Quick-access Pull Tab',
      'Use': 'First Aid / Medical / Rescue',
      'Color': 'Red / Black / Camo',
    },
  },
  {
    slug: 'tonmo-3l-hydration-backpack',
    sku: 'TM03001',
    nameEn: 'TONMO 3L Tactical Hydration Backpack',
    nameZh: 'TONMO 3L战术水袋背包',
    descriptionEn: 'Lightweight 3L tactical hydration backpack compatible with standard water bladders. MOLLE system for attachment to existing packs. Ideal for tactical operations, hiking, and outdoor activities where hydration on-the-go is essential.',
    descriptionZh: '轻量3L战术水袋背包，兼容标准水袋。MOLLE系统可挂载到现有背包。适合战术行动、徒步和户外活动。',
    shortDescEn: '3L tactical hydration backpack MOLLE compatible',
    shortDescZh: '3L战术水袋背包MOLLE兼容',
    categorySlug: 'tactical-backpacks',
    isFeatured: false,
    sortOrder: 19,
    moq: 100,
    specifications: {
      'Capacity': '3L',
      'Material': 'Nylon',
      'System': 'MOLLE',
      'Waterproof': 'Yes',
      'Use': 'Hydration / Outdoor / Tactical',
      'Colors': 'Black / Camo',
    },
  },
]

async function main() {
  console.log('Starting TONMO product upload...\n')

  // Get all categories
  const categories = await prisma.category.findMany()
  const categoryMap = new Map(categories.map(c => [c.slug, c.id]))
  console.log(`Found ${categories.length} categories: ${categories.map(c => c.slug).join(', ')}`)

  let created = 0
  let skipped = 0

  for (const product of tonmoProducts) {
    // Check if product already exists
    const existing = await prisma.product.findUnique({ where: { slug: product.slug } })
    if (existing) {
      console.log(`  SKIP: ${product.sku || product.slug} - already exists`)
      skipped++
      continue
    }

    const categoryId = product.categorySlug ? categoryMap.get(product.categorySlug) : null
    if (product.categorySlug && !categoryId) {
      console.log(`  WARN: Category "${product.categorySlug}" not found for ${product.sku}`)
    }

    await prisma.product.create({
      data: {
        slug: product.slug,
        sku: product.sku,
        nameEn: product.nameEn,
        nameZh: product.nameZh,
        descriptionEn: product.descriptionEn,
        descriptionZh: product.descriptionZh,
        shortDescEn: product.shortDescEn,
        shortDescZh: product.shortDescZh,
        isActive: true,
        isFeatured: product.isFeatured,
        isCustomizable: product.isCustomizable !== undefined ? product.isCustomizable : true,
        sortOrder: product.sortOrder || 0,
        moq: product.moq || null,
        specifications: product.specifications ? JSON.stringify(product.specifications) : null,
        categoryId: categoryId || null,
      },
    })

    console.log(`  OK: ${product.sku} - ${product.nameEn}`)
    created++
  }

  console.log(`\nDone! Created: ${created}, Skipped: ${skipped}`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })